dubbo:
  application:
    name: user-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    # 协议端口。使用 -1 表示随机端口。
    port: -1
    name: dubbo
  provider:
    # 【重要】远程服务调用超时时间，单位：毫秒。默认为 1000 毫秒
    timeout: 1000
    UserRpcService:
      version: 1.0.0