dubbo:
  application:
    name: dubbo-annotation-user-service-provider
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    port: -1
    name: dubbo
  provider:
    timeout: 1000
    UserRpcService:
      version: 1.0.0
  # 配置扫描 Dubbo 自定义的 @Service 注解，暴露成 Dubbo 服务提供者
  scan:
    base-packages: cn.fxbin.record.dubbo.rpc.provider.service